Add initial template of static site to subscription - issue #8
ES2-UFPI/404-spcpg-site pull request #4
Opened 2019-04-11 16:38 UTC by anapaulamendes

2019-04-16 18:51 UTC, gabriel-arauj requested changes

2019-04-16 18:51 UTC, gabriel-arauj commented on .gitignore
> +*.gem
Adicionar "gemfile.lock" na lista.

2019-04-16 18:51 UTC, gabriel-arauj commented on Gemfile.lock
> +GEM
Remover esse arquivo.

2019-04-17 22:32 UTC, anapaulamendes commented on .gitignore
> +*.gem
Adicionado. :smile:

2019-04-17 22:32 UTC, anapaulamendes commented on Gemfile.lock
> +GEM
Removido. :smile:

2019-04-17 23:33 UTC, gabriel-arauj approved these changes

2019-04-17 23:36 UTC, merged